states = [
 '',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chattisgarh',
 'Dadra and Nagar Haveli',
 'Daman and Diu',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Lakshadweep Islands',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Pondicherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal',
]

state_numbers = {
 "Andhra Pradesh": "37",
 "Arunachal Pradesh": "12",
 "Assam": "18",
 "Bihar": "10",
 "Chandigarh": "04",
 "Chattisgarh": "22",
 "Dadra and Nagar Haveli": "26",
 "Daman and Diu": "25",
 "Delhi": "07",
 "Goa": "30",
 "Gujarat": "24",
 "Haryana": "06",
 "Himachal Pradesh": "02",
 "Jammu and Kashmir": "01",
 "Jharkhand": "20",
 "Karnataka": "29",
 "Kerala": "32",
 "Lakshadweep Islands": "31",
 "Madhya Pradesh": "23",
 "Maharashtra": "27",
 "Manipur": "14",
 "Meghalaya": "17",
 "Mizoram": "15",
 "Nagaland": "13",
 "Odisha": "21",
 "Pondicherry": "34",
 "Punjab": "03",
 "Rajasthan": "08",
 "Sikkim": "11",
 "Tamil Nadu": "33",
 "Telangana": "36",
 "Tripura": "16",
 "Uttar Pradesh": "35",
 "Uttarakhand": "36",
 "West Bengal": "19"
}