from __future__ import unicode_literals
from six import iteritems

states = [
 '',
 'Andaman and Nicobar Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra and Nagar Haveli and Daman and Diu',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Ladakh',
 'Lakshadweep Islands',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Other Territory',
 'Pondicherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal',
]

state_numbers = {
 "Andaman and Nicobar Islands": "35",
 "Andhra Pradesh": "37",
 "Arunachal Pradesh": "12",
 "Assam": "18",
 "Bihar": "10",
 "Chandigarh": "04",
 "Chhattisgarh": "22",
 "Dadra and Nagar Haveli and Daman and Diu": "26",
 "Delhi": "07",
 "Goa": "30",
 "Gujarat": "24",
 "Haryana": "06",
 "Himachal Pradesh": "02",
 "Jammu and Kashmir": "01",
 "Jharkhand": "20",
 "Karnataka": "29",
 "Kerala": "32",
 "Ladakh": "38",
 "Lakshadweep Islands": "31",
 "Madhya Pradesh": "23",
 "Maharashtra": "27",
 "Manipur": "14",
 "Meghalaya": "17",
 "Mizoram": "15",
 "Nagaland": "13",
 "Odisha": "21",
 "Other Territory": "98",
 "Pondicherry": "34",
 "Punjab": "03",
 "Rajasthan": "08",
 "Sikkim": "11",
 "Tamil Nadu": "33",
 "Telangana": "36",
 "Tripura": "16",
 "Uttar Pradesh": "09",
 "Uttarakhand": "05",
 "West Bengal": "19",
}

number_state_mapping = {v: k for k, v in iteritems(state_numbers)}
