from __future__ import unicode_literals

states = [
 '',
 'Andaman and Nicobar Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra and Nagar Haveli',
 'Daman and Diu',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Lakshadweep Islands',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Other Territory',
 'Pondicherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal',
]

state_numbers = {
 "Andaman and Nicobar Islands": "35",
 "Andhra Pradesh": "37",
 "Arunachal Pradesh": "12",
 "Assam": "18",
 "Bihar": "10",
 "Chandigarh": "04",
 "Chhattisgarh": "22",
 "Dadra and Nagar Haveli": "26",
 "Daman and Diu": "25",
 "Delhi": "07",
 "Goa": "30",
 "Gujarat": "24",
 "Haryana": "06",
 "Himachal Pradesh": "02",
 "Jammu and Kashmir": "01",
 "Jharkhand": "20",
 "Karnataka": "29",
 "Kerala": "32",
 "Lakshadweep Islands": "31",
 "Madhya Pradesh": "23",
 "Maharashtra": "27",
 "Manipur": "14",
 "Meghalaya": "17",
 "Mizoram": "15",
 "Nagaland": "13",
 "Odisha": "21",
 "Other Territory": "98",
 "Pondicherry": "34",
 "Punjab": "03",
 "Rajasthan": "08",
 "Sikkim": "11",
 "Tamil Nadu": "33",
 "Telangana": "36",
 "Tripura": "16",
 "Uttar Pradesh": "09",
 "Uttarakhand": "05",
 "West Bengal": "19",
}

number_state_mapping = {
	"36": "Telangana",
	"34": "Pondicherry",
	"37": "Andhra Pradesh",
	"06": "Haryana",
	"02": "Himachal Pradesh",
	"30": "Goa",
	"22": "Chhattisgarh",
	"32": "Kerala",
	"25": "Daman and Diu",
	"31": "Lakshadweep Islands",
	"24": "Gujarat",
	"12": "Arunachal Pradesh",
	"27": "Maharashtra",
	"10": "Bihar",
	"16": "Tripura",
	"13": "Nagaland",
	"98": "Other Territory",
	"04": "Chandigarh",
	"11": "Sikkim",
	"01": "Jammu and Kashmir",
	"29": "Karnataka",
	"23": "Madhya Pradesh",
	"20": "Jharkhand",
	"17": "Meghalaya",
	"07": "Delhi",
	"15": "Mizoram",
	"05": "Uttarakhand",
	"18": "Assam",
	"26": "Dadra and Nagar Haveli",
	"21": "Odisha",
	"09": "Uttar Pradesh",
	"14": "Manipur",
	"08": "Rajasthan",
	"33": "Tamil Nadu",
	"03": "Punjab",
	"35": "Andaman and Nicobar Islands",
	"19": "West Bengal",
}