from erpnext.manufacturing.doctype.manufacturing_process.constants import (
    CALIBRATION_PROCESS,
    COOLING_PROCESS,
    DISTRIBUTION_PROCESS,
    HEATING_PROCESS,
    MIXING_PROCESS,
    POLISHING_PROCESS,
    PRESSING_PROCESS,
    QUALITY_CHECK_PROCESS,
    # QUARANTINE_PROCESS,
    TRIMMING_PROCESS,
)

WAREHOUSE_SUFFIX = "Warehouse"

SILOS_WAREHOUSE = f"Silos {WAREHOUSE_SUFFIX}"
MIXING_WAREHOUSE = f"{MIXING_PROCESS} {WAREHOUSE_SUFFIX}"
DISTRIBUTION_WAREHOUSE = f"{DISTRIBUTION_PROCESS} {WAREHOUSE_SUFFIX}"
PRESSING_WAREHOUSE = f"{PRESSING_PROCESS} {WAREHOUSE_SUFFIX}"
HEATING_WAREHOUSE = f"{HEATING_PROCESS} {WAREHOUSE_SUFFIX}"
COOLING_WAREHOUSE = f"{COOLING_PROCESS} {WAREHOUSE_SUFFIX}"
# QUARANTINE_WAREHOUSE = f"{QUARANTINE_PROCESS} {WAREHOUSE_SUFFIX}"
TRIMMING_WAREHOUSE = f"{TRIMMING_PROCESS} {WAREHOUSE_SUFFIX}"
CALIBRATION_WAREHOUSE = f"{CALIBRATION_PROCESS} {WAREHOUSE_SUFFIX}"
POLISHING_WAREHOUSE = f"{POLISHING_PROCESS} {WAREHOUSE_SUFFIX}"
QUALITY_CHECK_WAREHOUSE = f"{QUALITY_CHECK_PROCESS} {WAREHOUSE_SUFFIX}"
FINISHED_GOODS_WAREHOUSE = f"Finished Goods {WAREHOUSE_SUFFIX}"
