# Copyright (c) 2013, Web Notes Technologies Pvt. Ltd. and Contributors
# License: GNU General Public License v3. See license.txt

import webnotes

def execute():
	doctypes = [
	"Announcement",
	"Authorization Rules",
	"Blog Subscriber",
	"Books",
	"Call Log",
	"Call Log Details",
	"Campaign Expense",
	"Communication Log",
	"Compaint Note",
	"Company Control",
	"Competitor",
	"Complaint Detail",
	"Desktop Item",
	"DocType Label",
	"Employee Training",
	"Featured Item",
	"GL Control",
	"GL Mapper",
	"GL Mapper Detail",
	"Holiday Block List",
	"Holiday Block List Allow",
	"Holiday Block List Date",
	"Home Control",
	"Home Settings",
	"Item Parameter",
	"Item Parameter Value",
	"Lead Email CC Detail",
	"Manage Account",
	"Market Segment",
	"Multi Ledger Report Detail",
	"Naming Series Options",
	"Navigation Control",
	"Online Contact",
	"Order Reconciliation",
	"Order Reconciliation Detail",
	"Other Income Detail",
	"Partner Target Detail",
	"Permission Control",
	"Permission Rules",
	"Print Style",
	"Product Catalogue Control",
	"Product Group",
	"Product Settings",
	"Products Settings",
	"Profile Control",
	"Project Activity",
	"Project Activity Update",
	"Project Control",
	"Project Cost Breakup",
	"Related Page",
	"RV Detail",
	"Sales Browser Control",
	"Sandbox",
	"Search Criteria",
	"Series Detail",
	"Shipping Address",
	"SMS Receiver",
	"State",
	"TC Detail",
	"Territory Target Detail",
	"Timesheet",
	"Timesheet Detail",
	"Top Bar Settings",
	"Training Session",
	"Training Session Details",
	"Transfer Ownership",
	"Trash Control",
	"Trend Analyzer Control",
	"Update Delivery Date",
	"User Setting-Profile",
	"User Setting-Role Permission",
	"User Setting-Role User",
	"User Settings",
	"Valuation Control",
	"Website Product Category",
	"Workflow Action Detail",
	"Workflow Engine",
	"Workflow Rule",
	"Workflow Rule Detail"
	]
	
	for d in doctypes:
		webnotes.delete_doc("DocType", d)