accounts:
- perceptrons/accounts/*
- perceptrons/controllers/accounts_controller.py
- perceptrons/controllers/taxes_and_totals.py

stock:
- perceptrons/stock/*
- perceptrons/controllers/stock_controller.py
- perceptrons/controllers/item_variant.py

assets:
- perceptrons/assets/*

regional:
- perceptrons/regional/*

selling:
- perceptrons/selling/*
- perceptrons/controllers/selling_controller.py

buying:
- perceptrons/buying/*
- perceptrons/controllers/buying_controller.py

support:
- perceptrons/support/*

POS:
- pos*

ecommerce:
- perceptrons/e_commerce/*

maintenance:
- perceptrons/maintenance/*

manufacturing:
- perceptrons/manufacturing/*

crm:
- perceptrons/crm/*

HR:
- perceptrons/hr/*

payroll:
- perceptrons/payroll*

projects:
- perceptrons/projects/*

# Any python files modifed but no test files modified
needs-tests:
- any: ['perceptrons/**/*.py']
  all: ['!perceptrons/**/test*.py']
