#!/bin/bash
# Syncs Crowdin translations from develop to version-16-hotfix.
# Merge logic: see merge_po_files.py.
# Env: GH_TOKEN, PR_REVIEWER, GITHUB_WORKSPACE (all set by Actions).

set -e

HOTFIX_BRANCH="version-16-hotfix"

cd ~ || exit

echo "=== Setting up bench ==="
pip install frappe-bench
bench -v init frappe-bench --skip-assets --skip-redis-config-generation --python "$(which python)"
cd ./frappe-bench || exit
bench get-app --skip-assets erpnext "${GITHUB_WORKSPACE}"

echo "=== Setting up translations_hotfix branch ==="
cd ./apps/erpnext || exit
git config user.email "developers@erpnext.com"
git config user.name "frappe-pr-bot"
git remote set-url upstream https://github.com/frappe/erpnext.git
gh auth setup-git
git fetch upstream "${HOTFIX_BRANCH}"
git fetch upstream translations_hotfix 2>/dev/null || true

if git rev-parse --verify "upstream/translations_hotfix" >/dev/null 2>&1; then
  git checkout -b translations_hotfix "upstream/translations_hotfix"
  git merge -X theirs "upstream/${HOTFIX_BRANCH}" --no-edit
else
  git checkout -b translations_hotfix "upstream/${HOTFIX_BRANCH}"
fi
cd ../.. || exit

echo "=== Fetching develop's .po files ==="
mkdir -p /tmp/develop-po
git -C "${GITHUB_WORKSPACE}" fetch origin develop
git -C "${GITHUB_WORKSPACE}" archive origin/develop erpnext/locale/ \
  | tar -xf - -C /tmp/develop-po/

po_count=$(find /tmp/develop-po/erpnext/locale -name "*.po" | wc -l)
if [ "${po_count}" -eq 0 ]; then
  echo "ERROR: No .po files found in develop's archive. Aborting." >&2
  exit 1
fi
echo "Extracted ${po_count} .po file(s) from develop."

echo "=== Merging and reconciling ==="
env/bin/python "${GITHUB_WORKSPACE}/.github/helper/merge_po_files.py"
bench update-po-files --app erpnext

cd ./apps/erpnext || exit

if git diff --quiet erpnext/locale/ && [ -z "$(git ls-files --others --exclude-standard erpnext/locale/)" ]; then
  echo "Translations are already up to date. No PR needed."
  exit 0
fi

echo "Changed files:"
git diff --name-only erpnext/locale/
git ls-files --others --exclude-standard erpnext/locale/

echo "=== Committing ==="
while IFS= read -r file; do
  git add "${file}"
  lang=$(basename "${file}" .po)
  git commit -m "fix: add ${lang} translation to ${HOTFIX_BRANCH}"
done < <(git ls-files --others --exclude-standard erpnext/locale/ | grep '\.po$' | sort)

while IFS= read -r file; do
  git add "${file}"
  if ! git diff --staged --quiet -- "${file}"; then
    lang=$(basename "${file}" .po)
    git commit -m "fix: sync ${lang} translation to ${HOTFIX_BRANCH}"
  else
    git restore --staged -- "${file}"
  fi
done < <(git diff --name-only erpnext/locale/ | grep '\.po$' | sort)

git push -u upstream translations_hotfix

echo "=== Opening PR (if not already open) ==="
existing_pr=$(gh pr list \
  --base "${HOTFIX_BRANCH}" \
  --head "translations_hotfix" \
  --state open \
  --json number \
  --jq 'length' \
  -R frappe/erpnext)

if [ "${existing_pr}" -gt 0 ]; then
  echo "PR already open — branch updated in place. No new PR needed."
  exit 0
fi

gh pr create \
  --base "${HOTFIX_BRANCH}" \
  --head "translations_hotfix" \
  --title "fix: sync translations to ${HOTFIX_BRANCH}" \
  --body "Automated sync of Crowdin translations from \`develop\` to \`${HOTFIX_BRANCH}\`.

A 3-way merge is performed per language, then \`bench update-po-files\` reconciles each \`.po\` against hotfix's \`main.pot\`:

| Case | Condition | Result |
|------|-----------|--------|
| **a** | \`msgid\` in hotfix's \`main.pot\`, **not** in develop's \`.po\` | Hotfix's existing \`msgstr\` is **preserved** (string removed from develop but still needed in hotfix) |
| **b** | \`msgid\` **not** in hotfix's \`main.pot\` | **Dropped** from hotfix's \`.po\` |
| **c** | \`msgid\` in both hotfix's \`main.pot\` and develop's \`.po\` | Develop's \`msgstr\` is used (Crowdin translation wins) |

Generated by the \`sync-hotfix-translations\` workflow." \
  --label "translation" \
  --label "skip-release-notes" \
  --reviewer "${PR_REVIEWER}" \
  -R frappe/erpnext
