files:
  - source: /erpnext/locale/main.pot
    translation: /erpnext/locale/%two_letters_code%.po
pull_request_title: "fix: sync translations from crowdin"
pull_request_labels:
  - translation
commit_message: "fix: %language% translations"
append_commit_message: false
