MIXING_PROCESS = "Mixing"
DISTRIBUTION_PROCESS = "Distribution"
PRESSING_PROCESS = "Pressing"
HEATING_PROCESS = "Heating"
QUARANTINE_PROCESS = "Quarantine"
COOLING_PROCESS = "Cooling"
TRIMMING_PROCESS = "Trimming"
CALIBRATION_PROCESS = "Calibration"
# CALIBRATION_1_PROCESS = "Calibration 1"
# CALIBRATION_2_PROCESS = "Calibration 2"
POLISHING_PROCESS = "Polishing"
# POLISHING_1_PROCESS = "Polishing 1"
# POLISHING_2_PROCESS = "Polishing 2"
QUALITY_CHECK_PROCESS = "Quality Check"

ALL_MFG_PROCESSES = [
    MIXING_PROCESS,
    DISTRIBUTION_PROCESS,
    PRESSING_PROCESS,
    HEATING_PROCESS,
    QUARANTINE_PROCESS,
    COOLING_PROCESS,
    TRIMMING_PROCESS,
    CALIBRATION_PROCESS,
    POLISHING_PROCESS,
    QUALITY_CHECK_PROCESS,
]
