# Copyright (c) 2022, Betalogics and Contributors
# License: GNU General Public License v3. See license.txt


import frappe, os, json
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields
from frappe.custom.doctype.property_setter.property_setter import make_property_setter
from frappe.permissions import add_permission, update_permission_property
from frappe.utils import today

def setup(company=None, patch=True):
	# Company independent fixtures should be called only once at the first company setup
	if patch or frappe.db.count("Company", {"country": "Pakistan"}) <= 1:
		setup_company_independent_fixtures(patch=patch)

# TODO: for all countries
def setup_company_independent_fixtures(patch=False):
	make_custom_fields()

def make_custom_fields(update=True):
	custom_fields = get_custom_fields()
	create_custom_fields(custom_fields, update=update)

def get_custom_fields():

	custom_fields = {
		"Item":	[
			dict(
				fieldname="pct_code",
				label="PCT Code",
				fieldtype="Data",
				insert_after="item_group",
			),
		],
		"Supplier":[
			dict(
				bold=1,
				fieldname="ntn",
				label="NTN",
				fieldtype="Data",
				insert_after= "tax_id",
				name="Supplier-ntn",
			),
			dict(
				bold=1,
				fieldname="strn",
				label="STRN",
				fieldtype="Data",
				insert_after= "ntn",
				name="Supplier-strn",
			),
			dict(
				bold=1,
				fieldname="cnic",
				label="CNIC",
				fieldtype="Data",
				insert_after= "strn",
				name="Supplier-cnic",
			),
		],
		"Quotation":[
			dict(
				fetch_from= "party_name.ntn",
				bold=1,
				fieldname="ntn",
				label="NTN",
				fieldtype="Data",
				insert_after= "customer_name",
				name="Quotation-ntn",
				read_only=1,
				depends_on='eval: in_list(["Customer"], doc.quotation_to)',
			),
			dict(
				fetch_from= "party_name.strn",
				bold=1,
				fieldname="strn",
				label="STRN",
				fieldtype="Data",
				insert_after= "ntn",
				name="Quotation-strn",
				read_only=1,
				depends_on='eval: in_list(["Customer"], doc.quotation_to)',
			),
			dict(
				fetch_from= "party_name.cnic",
				bold=1,
				fieldname="cnic",
				label="CNIC",
				fieldtype="Data",
				insert_after= "strn",
				name="Quotation-cnic",
				read_only=1,
				depends_on='eval: in_list(["Customer"], doc.quotation_to)',
			),
		],
		"Quotation Item": [
			  dict(
				dt="Quotation Item",
				fetch_from="item_code.pct_code",
				bold=1,
				fieldname="pct_code",
				label="PCT Code",
				fieldtype="Data",
				insert_after= "item_name",
				name="Quotation Item-pct_code",
				read_only=1,
			),
		],
		"Purchase Order":[
			dict(
				fetch_from= "supplier.ntn",
				bold=1,
				fieldname="ntn",
				label="NTN",
				fieldtype="Data",
				insert_after= "supplier_name",
				name="Purchase Order-ntn",
				read_only=1,
			),
			dict(
				fetch_from= "supplier.strn",
				bold=1,
				fieldname="strn",
				label="STRN",
				fieldtype="Data",
				insert_after= "ntn",
				name="Purchase Order-strn",
				read_only=1,
			),
			dict(
				fetch_from= "supplier.cnic",
				bold=1,
				fieldname="cnic",
				label="CNIC",
				fieldtype="Data",
				insert_after= "strn",
				name="Purchase Order-cnic",
				read_only=1,
			),
		],
		"Purchase Receipt": [
			dict(
				dt="Purchase Receipt",
				fetch_from="supplier.ntn",
				bold=1,
				fieldname="ntn",
				label="NTN",
				fieldtype="Data",
				insert_after= "supplier_name",
				name="Purchase Receipt-ntn",
				read_only=1,
			),
			dict(
				dt="Purchase Receipt",
				fetch_from="supplier.strn",
				bold=1,
				fieldname="strn",
				label="STRN",
				fieldtype="Data",
				insert_after= "ntn",
				name="Purchase Receipt-strn",
				read_only=1,
			),
			dict(
				dt="Purchase Receipt",
				fetch_from="supplier.cnic",
				bold=1,
				fieldname="cnic",
				label="CNIC",
				fieldtype="Data",
				insert_after= "strn",
				name="Purchase Receipt-cnic",
				read_only=1,
			),
		],
		"Purchase Invoice":[
			dict(
				dt="Purchase Invoice",
				fetch_from="supplier.ntn",
				bold=1,
				fieldname="ntn",
				label="NTN",
				fieldtype="Data",
				insert_after= "tax_id",
				name="Purchase Invoice-ntn",
				read_only=1,
			),
			dict(
				dt="Purchase Invoice",
				fetch_from="supplier.strn",
				bold=1,
				fieldname="strn",
				label="STRN",
				fieldtype="Data",
				insert_after= "ntn",
				name="Purchase Invoice-strn",
				read_only=1,
			),
			dict(
				dt="Purchase Invoice",
				fetch_from="supplier.cnic",
				bold=1,
				fieldname="cnic",
				label="CNIC",
				fieldtype="Data",
				insert_after= "strn",
				name="Purchase Invoice-cnic",
				read_only=1,
			),
		],
		"Purchase Order Item":[
			dict(
				dt="Purchase Order Item",
				fetch_from="item_code.pct_code",
				bold=1,
				fieldname="pct_code",
				label="PCT Code",
				fieldtype="Data",
				insert_after= "item_name",
				name="Purchase Order Item-pct_code",
    			read_only=1,
			),
		],
		"Purchase Receipt Item":[
			dict(
				dt="Purchase Receipt Item",
				fetch_from="item_code.pct_code",
				bold=1,
				fieldname="pct_code",
				label="PCT Code",
				fieldtype="Data",
				insert_after= "item_name",
				name="Purchase Receipt Item-pct_code",
				read_only=1,
			),
		],
		"Purchase Invoice Item":[
			dict(
				dt="Purchase Invoice Item",
				fetch_from="item_code.pct_code",
				bold=1,
				fieldname="pct_code",
				label="PCT Code",
				fieldtype="Data",
				insert_after= "item_name",
				name="Purchase Invoice Item-pct_code",
				read_only=1,
			),
		],
		"Customer":[
			dict(
				dt="Customer",
				bold=1,
				fieldname="ntn",
				label="NTN",
				fieldtype="Data",
				insert_after= "tax_id",
				name="Customer-ntn",
			),
			dict(
				dt="Customer",
				bold=1,
				fieldname="strn",
				label="STRN",
				fieldtype="Data",
				insert_after= "ntn",
				name="Customer-strn",
			),
			dict(
				dt="Customer",
				bold=1,
				fieldname="cnic",
				label="CNIC",
				fieldtype="Data",
				insert_after= "strn",
				name="Customer-cnic",
			),
		],
		"Sales Order":[
			dict(
				dt="Sales Order",
				fetch_from= "customer.ntn",
				bold=1,
				fieldname="ntn",
				label="NTN",
				fieldtype="Data",
				insert_after= "tax_id",
				name="Sales Order-ntn",
				read_only=1,
			),
			
			dict(
				dt="Sales Order",
				fetch_from= "customer.strn",
				bold=1,
				fieldname="strn",
				label="STRN",
				fieldtype="Data",
				insert_after= "ntn",
				name="Sales Order-strn",
				read_only=1,
			),
			dict(
				dt="Sales Order",
				fetch_from= "customer.cnic",
				bold=1,
				fieldname="cnic",
				label="CNIC",
				fieldtype="Data",
				insert_after= "strn",
				name="Sales Order-cnic",
				read_only=1,
			),
		],
		"Sales Order Item":[
			dict(
				dt="Sales Order Item",
				fetch_from="item_code.pct_code",
				bold=1,
				fieldname="pct_code",
				label="PCT Code",
				fieldtype="Data",
				insert_after= "item_name",
				name="Sales Order Item-pct_code",
				read_only=1,
			),
		],
		"Delivery Note":[
			 dict(
				dt="Delivery Note",
				fetch_from= "customer.ntn",
				bold=1,
				fieldname="ntn",
				label="NTN",
				fieldtype="Data",
				insert_after= "tax_id",
				name="Delivery Note-ntn",
				read_only=1,
			),
			dict(
				dt="Delivery Note",
				fetch_from= "customer.strn",
				bold=1,
				fieldname="strn",
				label="STRN",
				fieldtype="Data",
				insert_after= "ntn",
				name="Delivery Note-strn",
				read_only=1,
			),
			dict(
				dt="Delivery Note",
				fetch_from= "customer.cnic",
				bold=1,
				fieldname="cnic",
				label="CNIC",
				fieldtype="Data",
				insert_after= "strn",
				name="Delivery Note-cnic",
				read_only=1,
			),
		],
		"Delivery Note Item":[
			dict(
				dt="Delivery Note Item",
				fetch_from="item_code.pct_code",
				bold=1,
				fieldname="pct_code",
				label="PCT Code",
				fieldtype="Data",
				insert_after= "item_name",
				name="Delivery Note Item-pct_code",
				read_only=1,
			),
		],
		"Sales Invoice":[
			 dict(
				dt="Sales Invoice",
				fetch_from= "customer.ntn",
				bold=1,
				fieldname="ntn",
				label="NTN",
				fieldtype="Data",
				insert_after= "tax_id",
				name="Sales Invoice-ntn",
				read_only=1,
			),
			dict(
				dt="Sales Invoice",
				fetch_from= "customer.strn",
				bold=1,
				fieldname="strn",
				label="STRN",
				fieldtype="Data",
				insert_after= "ntn",
				name="Sales Invoice-strn",
				read_only=1,
			),
			dict(
				dt="Sales Invoice",
				fetch_from= "customer.cnic",
				bold=1,
				fieldname="cnic",
				label="CNIC",
				fieldtype="Data",
				insert_after= "strn",
				name="Sales Invoice-cnic",
				read_only=1,
			),
		],
		"Sales Invoice Item":[
			dict(
				dt="Sales Invoice Item",
				fetch_from="item_code.pct_code",
				bold=1,
				fieldname="pct_code",
				label="PCT Code",
				fieldtype="Data",
				insert_after= "item_name",
				name="Sales Invoice Item-pct_code",
				read_only=1,
			),
		],
		"Company": [
			dict(
				bold=1,
				fieldname="ntn",
				label="NTN",
				fieldtype="Data",
				insert_after= "tax_id",
				name="Company-ntn",
			),
			dict(
				bold=1,
				fieldname="strn",
				label="STRN",
				fieldtype="Data",
				insert_after= "ntn",
				name="Company-strn",
			),
			dict(
				bold=1,
				fieldname="cnic",
				label="CNIC",
				fieldtype="Data",
				insert_after= "strn",
				name="Company-cnic",
			),
		],
 	}

	return custom_fields