# Copyright (c) 2017, Frappe Technologies Pvt. Ltd. and contributors
# For license information, please see license.txt

"""Alternative-item substitution for a Production Plan.

The sub-assembly and raw-material tables of a Production Plan are generated by
exploding BOMs, so their rows are not hand-editable. This service is the one
supported way to swap a generated row's item for a declared ``Item Alternative``
and keep everything that hangs off that row coherent:

* the row's own item details, UOM/conversion and bin figures are refreshed,
* a sub-assembly swap also re-points the row at the alternative's BOM and
  re-labels the raw-material rows exploded through it,
* Stock Reservation Entries held by the plan for the original item are released
  and re-made against the alternative (submitted plans only -- a draft plan has
  not reserved anything yet, it reserves on submit),
* Bin ``reserved_qty_for_production_plan`` is recomputed for both the original
  and the alternative item, and
* draft Work Orders already raised from the plan are updated in place, so the
  substitution reaches production rather than being silently reverted by the BOM.

A row that has already made progress (a submitted Work Order, Purchase Order or
Material Request) cannot be substituted; the message says which document blocks it.
"""

import frappe
from frappe import _
from frappe.utils import flt, parse_json

from erpnext.manufacturing.doctype.bom.bom import get_bom_items_as_dict
from erpnext.manufacturing.doctype.production_plan.services.planning_queries import get_bin_details
from erpnext.manufacturing.doctype.production_plan.services.reservation import (
	reserve_stock_for_production_plan,
)
from erpnext.stock.doctype.item_alternative.item_alternative import (
	get_alternative_item_codes,
	validate_alternative_item,
)
from erpnext.stock.doctype.stock_reservation_entry.stock_reservation_entry import StockReservation
from erpnext.stock.utils import get_or_make_bin

_TABLES = {
	"sub_assembly_items": frappe._dict(
		{
			"child_doctype": "Production Plan Sub Assembly Item",
			"item_field": "production_item",
			"warehouse_field": "fg_warehouse",
			"qty_field": "required_qty",
			"bin_method": "update_reserved_qty_for_for_sub_assembly",
		}
	),
	"mr_items": frappe._dict(
		{
			"child_doctype": "Material Request Plan Item",
			"item_field": "item_code",
			"warehouse_field": "warehouse",
			"qty_field": "required_bom_qty",
			"bin_method": "update_reserved_qty_for_production_plan",
		}
	),
}

# Written back on the child row when a substitution is applied. Everything else on the
# row (quantities, warehouse, schedule, sales order links) is deliberately preserved.
_SUB_ASSEMBLY_UPDATE_FIELDS = (
	"production_item",
	"original_item",
	"item_name",
	"description",
	"stock_uom",
	"uom",
	"bom_no",
	"supplier",
	"actual_qty",
	"projected_qty",
)
_MR_UPDATE_FIELDS = (
	"item_code",
	"original_item",
	"item_name",
	"description",
	"uom",
	"conversion_factor",
	"quantity",
	"min_order_qty",
	"safety_stock",
	"actual_qty",
	"projected_qty",
	"ordered_qty",
	"reserved_qty_for_production",
)


class AlternativeItemService:
	def __init__(self, doc):
		self.doc = doc

	# ------------------------------------------------------------------ read

	def get_substitutable_rows(self, table_name: str) -> list[dict]:
		"""Rows of ``table_name`` whose item declares at least one Item Alternative."""
		config = _config(table_name)
		rows = []
		for row in self.doc.get(table_name):
			item_code = row.get(config.item_field)
			if not item_code or not frappe.get_cached_value("Item", item_code, "allow_alternative_item"):
				continue
			if not get_alternative_item_codes(item_code):
				continue

			rows.append(
				{
					"docname": row.name,
					"idx": row.idx,
					"item_code": item_code,
					"original_item": row.get("original_item"),
					"warehouse": row.get(config.warehouse_field),
					"qty": flt(row.get(config.qty_field)),
					"uom": row.get("uom") or row.get("stock_uom"),
					"bom_no": row.get("bom_no"),
					"blocked_by": self._blocking_reason(row, table_name),
				}
			)
		return rows

	# ----------------------------------------------------------------- write

	def substitute(self, table_name: str, substitutions: str | list) -> None:
		config = _config(table_name)
		substitutions = parse_json(substitutions) if isinstance(substitutions, str) else substitutions
		self._validate_plan_state()

		changes = self._collect_changes(table_name, config, substitutions)
		if not changes:
			frappe.msgprint(_("No items were substituted."), alert=True)
			return

		bins_to_update = {(c.old_item, c.warehouse) for c in changes}

		if self.doc.docstatus == 1:
			self._release_reservations(changes, table_name)

		for change in changes:
			self._apply(change, table_name)
			bins_to_update.add((change.new_item, change.warehouse))

		if self.doc.docstatus == 0:
			self.doc.save()
		else:
			self._persist_submitted(changes, config)
			self._propagate_to_work_orders(changes, table_name)
			self._reserve(changes, table_name)

		self._update_bins(bins_to_update, config)
		self.doc.reload()

		frappe.msgprint(
			_("Substituted {0} item(s).").format(len(changes))
			+ "<br>"
			+ "<br>".join(
				_("Row #{0}: {1} &rarr; {2}").format(c.row.idx, c.old_item, c.new_item) for c in changes
			),
			title=_("Alternate Item"),
			indicator="green",
		)

	# ------------------------------------------------------------ validation

	def _validate_plan_state(self):
		self.doc.check_permission("write")

		if self.doc.docstatus == 2:
			frappe.throw(_("Cannot substitute items on a cancelled Production Plan."))

		if self.doc.status in ("Completed", "Closed"):
			frappe.throw(_("Cannot substitute items on a {0} Production Plan.").format(_(self.doc.status)))

	def _collect_changes(self, table_name, config, substitutions):
		rows = {row.name: row for row in self.doc.get(table_name)}
		changes = []
		seen = set()

		for entry in substitutions or []:
			entry = frappe._dict(entry)
			row = rows.get(entry.docname)
			if not row:
				frappe.throw(
					_("Row {0} was not found in {1}. Please reopen the dialog and try again.").format(
						frappe.bold(entry.docname), frappe.bold(_(self.doc.meta.get_label(table_name)))
					)
				)

			old_item = row.get(config.item_field)
			new_item = entry.alternate_item
			if not new_item or new_item == old_item:
				continue

			if row.name in seen:
				frappe.throw(_("Row #{0} was substituted twice in the same request.").format(row.idx))
			seen.add(row.name)

			validate_alternative_item(old_item, new_item)
			self._validate_row_is_substitutable(row, table_name)

			change = frappe._dict(
				{
					"row": row,
					"old_item": old_item,
					"new_item": new_item,
					"warehouse": row.get(config.warehouse_field),
					"old_bom_no": row.get("bom_no"),
					"new_bom_no": None,
				}
			)
			if table_name == "sub_assembly_items":
				change.new_bom_no = self._resolve_bom(new_item, entry.bom_no)
				self._validate_raw_material_impact(change)

			changes.append(change)

		return changes

	def _validate_row_is_substitutable(self, row, table_name):
		if reason := self._blocking_reason(row, table_name):
			frappe.throw(
				_("Row #{0}: {1} cannot be substituted. {2}").format(
					row.idx,
					frappe.bold(row.get(_config(table_name).item_field)),
					reason,
				),
				title=_("Substitution Not Allowed"),
			)

	def _blocking_reason(self, row, table_name) -> str | None:
		"""Human-readable reason the row cannot be substituted, or None."""
		if table_name == "sub_assembly_items":
			return self._sub_assembly_blocking_reason(row)
		return self._mr_blocking_reason(row)

	def _sub_assembly_blocking_reason(self, row):
		if flt(row.ordered_qty) or flt(row.wo_produced_qty) or flt(row.received_qty):
			return _("A Work Order or Subcontracting PO has already been raised against it.")

		if row.purchase_order:
			return _("It is linked to Purchase Order {0}.").format(row.purchase_order)

		submitted_wo = frappe.get_all(
			"Work Order",
			filters={"production_plan_sub_assembly_item": row.name, "docstatus": ("!=", 0)},
			pluck="name",
			limit=1,
		)
		if submitted_wo:
			return _("Work Order {0} has already been submitted against it.").format(submitted_wo[0])
		return None

	def _mr_blocking_reason(self, row):
		if flt(row.requested_qty):
			return _("A Material Request has already been raised against it.")

		submitted_mr = frappe.get_all(
			"Material Request Item",
			filters={"material_request_plan_item": row.name, "docstatus": ("!=", 0)},
			fields=["parent"],
			pluck="parent",
			limit=1,
		)
		if submitted_mr:
			return _("Material Request {0} has already been submitted against it.").format(submitted_mr[0])
		return None

	def _resolve_bom(self, item_code, bom_no=None):
		if bom_no:
			bom = frappe.db.get_value("BOM", bom_no, ["item", "is_active"], as_dict=True)
			if not bom or bom.item != item_code:
				frappe.throw(_("BOM {0} does not belong to the item {1}.").format(bom_no, item_code))
			if not bom.is_active:
				frappe.throw(_("BOM {0} is not active.").format(bom_no))
			return bom_no

		default_bom = frappe.db.get_value(
			"BOM", {"item": item_code, "is_active": 1, "is_default": 1, "docstatus": 1}, "name"
		)
		if not default_bom:
			frappe.throw(
				_("No default BOM found for the alternative item {0}. Select a BOM explicitly.").format(
					frappe.bold(item_code)
				),
				title=_("BOM Missing"),
			)
		return default_bom

	def _validate_raw_material_impact(self, change):
		"""A sub-assembly swap changes which raw materials the plan needs.

		The raw-material table is exploded from the top-level BOMs and aggregated, so it
		cannot be patched row by row. When the two BOMs consume the same components in the
		same proportion there is nothing to do; otherwise a draft plan drops the table so
		the user re-fetches it, and a submitted plan refuses the swap.
		"""
		if self._components_match(change.old_bom_no, change.new_bom_no):
			return

		if not self.doc.mr_items:
			return

		if self.doc.docstatus == 1:
			frappe.throw(
				_(
					"BOM {0} of the alternative item {1} does not use the same raw materials as BOM {2}. "
					"The raw materials of a submitted Production Plan cannot be re-fetched, so this "
					"substitution is not possible. Cancel and amend the plan, or pick an alternative "
					"whose BOM uses the same raw materials."
				).format(
					frappe.bold(change.new_bom_no),
					frappe.bold(change.new_item),
					frappe.bold(change.old_bom_no),
				),
				title=_("Raw Materials Differ"),
			)

		change.clear_raw_materials = True

	def _components_match(self, old_bom_no, new_bom_no) -> bool:
		if old_bom_no == new_bom_no:
			return True
		if not old_bom_no or not new_bom_no:
			return False

		return self._components_per_unit(old_bom_no) == self._components_per_unit(new_bom_no)

	def _components_per_unit(self, bom_no):
		precision = frappe.get_precision("BOM Item", "qty")
		items = get_bom_items_as_dict(bom_no, self.doc.company, qty=1, fetch_exploded=1)
		return {item_code: flt(item.qty, precision) for item_code, item in items.items()}

	# ----------------------------------------------------------------- apply

	def _apply(self, change, table_name):
		if table_name == "sub_assembly_items":
			self._apply_sub_assembly(change)
		else:
			self._apply_raw_material(change)

		if change.get("clear_raw_materials"):
			self.doc.set("mr_items", [])
			frappe.msgprint(
				_(
					"The raw materials of BOM {0} differ from BOM {1}. The Raw Materials table has been "
					"cleared -- please fetch it again."
				).format(frappe.bold(change.new_bom_no), frappe.bold(change.old_bom_no)),
				title=_("Fetch Raw Materials Again"),
				indicator="orange",
			)

	def _apply_sub_assembly(self, change):
		row = change.row
		details = _item_details(change.new_item)
		bin_qty = self._bin_qty(change.new_item, change.warehouse)

		row.original_item = row.original_item or change.old_item
		row.production_item = change.new_item
		row.item_name = details.item_name
		row.description = details.description
		row.stock_uom = details.stock_uom
		row.uom = details.stock_uom
		row.bom_no = change.new_bom_no
		row.actual_qty = bin_qty.actual_qty
		row.projected_qty = bin_qty.projected_qty

		if row.type_of_manufacturing == "Subcontract":
			row.supplier = frappe.db.get_value(
				"Item Default",
				{"parent": change.new_item, "default_supplier": ("is", "set")},
				"default_supplier",
			)

		self._relabel_dependent_raw_materials(change)

	def _relabel_dependent_raw_materials(self, change):
		"""Raw-material rows exploded through this sub-assembly record it as their source.

		``ProductionPlan.add_reference_to_raw_materials`` matches those rows back to the
		sub-assembly on (production_item, bom_no) at submit time, so both must follow the swap
		or the reference is lost and reservation of the raw materials fails.
		"""
		change.relabelled_raw_materials = []
		for item in self.doc.mr_items:
			if item.main_item_code == change.old_item and item.from_bom == change.old_bom_no:
				item.main_item_code = change.new_item
				item.from_bom = change.new_bom_no
				change.relabelled_raw_materials.append(item.name)

	def _apply_raw_material(self, change):
		row = change.row
		details = _item_details(change.new_item)
		bin_qty = self._bin_qty(change.new_item, change.warehouse)

		# `quantity` is carried in the row's own UOM; keep the stock quantity the row stands for
		# unchanged while moving it onto the alternative item's UOM and conversion.
		old_conversion_factor = flt(row.conversion_factor) or 1.0
		new_uom, new_conversion_factor = _row_uom_and_conversion(change.new_item, row.material_request_type)
		stock_quantity = flt(row.quantity) * old_conversion_factor

		row.original_item = row.original_item or change.old_item
		row.item_code = change.new_item
		row.item_name = details.item_name
		row.description = details.description
		row.uom = new_uom
		row.conversion_factor = new_conversion_factor
		row.quantity = flt(
			stock_quantity / new_conversion_factor,
			frappe.get_precision("Material Request Plan Item", "quantity"),
		)
		row.min_order_qty = flt(details.min_order_qty)
		row.safety_stock = flt(details.safety_stock)
		row.actual_qty = bin_qty.actual_qty
		row.projected_qty = bin_qty.projected_qty
		row.ordered_qty = bin_qty.ordered_qty
		row.reserved_qty_for_production = bin_qty.reserved_qty_for_production

	def _bin_qty(self, item_code, warehouse):
		empty = frappe._dict(
			{"actual_qty": 0.0, "projected_qty": 0.0, "ordered_qty": 0.0, "reserved_qty_for_production": 0.0}
		)
		if not warehouse:
			return empty

		bin_details = get_bin_details({"item_code": item_code}, self.doc.company, for_warehouse=warehouse)
		return frappe._dict(bin_details[0]) if bin_details else empty

	def _persist_submitted(self, changes, config):
		"""Write the substituted rows of a submitted plan straight to the database.

		The item fields are not ``allow_on_submit`` on purpose -- the grid must stay read-only
		after submit; substitution is only ever reached through this service.
		"""
		fields = (
			_SUB_ASSEMBLY_UPDATE_FIELDS
			if config.child_doctype == "Production Plan Sub Assembly Item"
			else _MR_UPDATE_FIELDS
		)
		for change in changes:
			row = change.row
			frappe.db.set_value(config.child_doctype, row.name, {field: row.get(field) for field in fields})

		relabelled = set()
		for change in changes:
			relabelled.update(change.get("relabelled_raw_materials") or [])

		for item in self.doc.mr_items:
			if item.name in relabelled:
				frappe.db.set_value(
					"Material Request Plan Item",
					item.name,
					{"main_item_code": item.main_item_code, "from_bom": item.from_bom},
				)

	# ----------------------------------------------------------- reservation

	def _release_reservations(self, changes, table_name):
		"""Cancel the plan's Stock Reservation Entries held for the original items.

		Cancelling each entry updates the Bin and the row's ``stock_reserved_qty`` through the
		Stock Reservation Entry's own lifecycle, so no manual bookkeeping is needed here.
		"""
		names = []
		for change in changes:
			names.extend(self._reservation_names(change.old_item, change.warehouse, table_name))

		if names:
			StockReservation(self.doc).cancel_stock_reservation_entries(names)

	def _reservation_names(self, item_code, warehouse, table_name):
		entries = frappe.get_all(
			"Stock Reservation Entry",
			filters={
				"voucher_type": "Production Plan",
				"voucher_no": self.doc.name,
				"item_code": item_code,
				"warehouse": warehouse,
				"docstatus": 1,
			},
			fields=["name", "voucher_detail_no"],
		)
		# The two plan tables can reserve the same item in the same warehouse. Entries are told
		# apart by whether their voucher_detail_no is a raw-material row of this plan.
		mr_row_names = {row.name for row in self.doc.mr_items}
		wants_mr_rows = table_name == "mr_items"
		return [
			entry.name for entry in entries if ((entry.voucher_detail_no in mr_row_names) is wants_mr_rows)
		]

	def _reserve(self, changes, table_name):
		if not self.doc.reserve_stock:
			return

		self.doc.reload()
		changed = {change.row.name for change in changes}
		items = [row for row in self.doc.get(table_name) if row.name in changed]
		if items:
			reserve_stock_for_production_plan(self.doc, items=items, table_name=table_name)

	def _update_bins(self, bins_to_update, config):
		for item_code, warehouse in bins_to_update:
			if not item_code or not warehouse:
				continue
			bin_doc = frappe.get_doc("Bin", get_or_make_bin(item_code, warehouse), for_update=True)
			getattr(bin_doc, config.bin_method)()

	# ----------------------------------------------------------- work orders

	def _propagate_to_work_orders(self, changes, table_name):
		"""Carry the substitution into the Work Orders already raised from this plan.

		Only draft Work Orders are touched; a submitted one is blocked earlier by
		``_blocking_reason``. Without this the alternative would be silently reverted, because
		a Work Order's required items are re-read from the BOM, which still lists the original.
		"""
		substitutions = {change.old_item: change for change in changes}

		for name in self._draft_work_orders():
			wo = frappe.get_doc("Work Order", name)
			touched = False

			if table_name == "sub_assembly_items":
				touched = self._substitute_work_order_output(wo, substitutions) or touched

			touched = self._substitute_work_order_inputs(wo, substitutions) or touched

			if touched:
				wo.flags.ignore_validate = True
				wo.save()

	def _draft_work_orders(self):
		return frappe.get_all(
			"Work Order", filters={"production_plan": self.doc.name, "docstatus": 0}, pluck="name"
		)

	def _substitute_work_order_output(self, wo, substitutions):
		change = substitutions.get(wo.production_item)
		if not change or wo.production_plan_sub_assembly_item != change.row.name:
			return False

		details = _item_details(change.new_item)
		wo.production_item = change.new_item
		wo.item_name = details.item_name
		wo.description = details.description
		wo.stock_uom = details.stock_uom
		wo.bom_no = change.new_bom_no
		wo.set_required_items()
		return True

	def _substitute_work_order_inputs(self, wo, substitutions):
		touched = False
		for item in wo.required_items:
			change = substitutions.get(item.item_code)
			if not change:
				continue

			details = _item_details(change.new_item)
			item.original_item = item.original_item or item.item_code
			item.item_code = change.new_item
			item.item_name = details.item_name
			item.description = details.description
			item.stock_uom = details.stock_uom
			item.allow_alternative_item = 1
			touched = True

		if touched:
			wo.allow_alternative_item = 1
		return touched


def _config(table_name):
	config = _TABLES.get(table_name)
	if not config:
		frappe.throw(_("Alternative items are not supported for the table {0}.").format(table_name))
	return config


def _item_details(item_code):
	return frappe.get_cached_value(
		"Item",
		item_code,
		["item_name", "description", "stock_uom", "purchase_uom", "min_order_qty", "safety_stock"],
		as_dict=True,
	)


def _row_uom_and_conversion(item_code, material_request_type):
	"""The raw-material row's UOM and its stock-qty-per-unit, as the row was originally built.

	Only a purchase row is carried in the item's purchase UOM; a transfer row stays in stock UOM.
	"""
	from erpnext.stock.get_item_details import get_conversion_factor

	details = frappe.get_cached_value("Item", item_code, ["purchase_uom", "stock_uom"], as_dict=True)
	if material_request_type != "Purchase" or not details.purchase_uom:
		return details.stock_uom, 1.0

	if details.purchase_uom == details.stock_uom:
		return details.stock_uom, 1.0

	conversion_factor = get_conversion_factor(item_code, details.purchase_uom).get("conversion_factor")
	return details.purchase_uom, conversion_factor or 1.0


@frappe.whitelist()
def get_substitutable_rows(production_plan: str, table_name: str):
	doc = frappe.get_doc("Production Plan", production_plan)
	doc.check_permission("read")
	return AlternativeItemService(doc).get_substitutable_rows(table_name)


@frappe.whitelist()
def substitute_alternative_items(production_plan: str, table_name: str, substitutions: str | list):
	doc = frappe.get_doc("Production Plan", production_plan)
	AlternativeItemService(doc).substitute(table_name, substitutions)
