name: Review translation PRs
description: "Posts review comments with relevant translation changes that are hard to inspect in the diff view."

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - "**/*.po"
      - "**/*.pot"

concurrency:
  group: po-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  review-po-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - uses: alyf-de/po-review-action@v1.0.0
